[package]
name = "bevy_2"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2" }
bevy-inspector-egui = "0.27.0"
bevy_editor_pls = "0.10.0"
bevy_rapier3d = "0.27.0"
serde = { version = "1.0.214", features = ["derive"] }

[workspace]
resolver = "2"
